openapi: 3.0.0
info:
  title: Region Sjælland Testkomponent
  description: API description for Region Sjælland Testkomponent.
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: Testkompoent
    description: Testkomponent related API's

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /rest/v1/context:
    get:
      tags:
        - KITHUGS
      summary: Show user context
      description: Return user context.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contextResponse'

components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    contextResponse:
      type: object
      required:
        - context
      properties:
        context:
          type: array
          items:
            $ref: '#/components/schemas/context'
          description: The context received in the call.

    context:
      type: object
      required:
        - attributeName
        - attributeValue
      properties:
        attributeName:
          description: The context attribute name.
          type: string
        attributeValue:
          description: The context attribute value.
          type: array
          items:
            type: string

